"""schema inicial producao

Revision ID: b95009c1442e
Revises: 
Create Date: 2026-08-06 01:18:34.051287
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b95009c1442e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cardapio_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_refeicao', sa.String(), nullable=False),
    sa.Column('tipo_refeicao', sa.String(), nullable=False),
    sa.CheckConstraint("tipo_refeicao IN ('Lanche', 'Almoço', 'Janta')", name='ck_cardapio_tipo_refeicao'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cardapio_itens_id'), 'cardapio_itens', ['id'], unique=False)
    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fornecedores_id'), 'fornecedores', ['id'], unique=False)
    op.create_index(op.f('ix_fornecedores_nome'), 'fornecedores', ['nome'], unique=False)
    op.create_table('itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('unidade_oficial', sa.String(), nullable=False),
    sa.Column('saldo_atual', sa.Float(), nullable=True),
    sa.Column('unidade_interna', sa.String(), nullable=True),
    sa.Column('fator_conversao', sa.Float(), nullable=True),
    sa.Column('limiar', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_id'), 'itens', ['id'], unique=False)
    op.create_index(op.f('ix_itens_nome'), 'itens', ['nome'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('perfil', sa.String(), nullable=False),
    sa.CheckConstraint("perfil IN ('admin', 'secretaria', 'cozinheira')", name='ck_usuarios_perfil'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_nome'), 'usuarios', ['nome'], unique=True)
    op.create_table('alunos_por_periodo',
    sa.Column('periodo', sa.String(), nullable=False),
    sa.Column('qtd', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('periodo')
    )
    op.create_table('conversoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('medida_caseira', sa.String(), nullable=False),
    sa.Column('peso_em_kg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['itens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'medida_caseira', name='uq_conversoes_item_medida')
    )
    op.create_index(op.f('ix_conversoes_id'), 'conversoes', ['id'], unique=False)
    op.create_table('entregas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('origem', sa.String(), nullable=False),
    sa.Column('data_entrega', sa.Date(), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('nota_numero', sa.String(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entregas_id'), 'entregas', ['id'], unique=False)
    op.create_table('planejamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cardapio_item_id', sa.Integer(), nullable=False),
    sa.Column('tipo_refeicao', sa.String(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('data_inicio_vigencia', sa.Date(), nullable=False),
    sa.CheckConstraint('dia_semana BETWEEN 0 AND 6', name='ck_planejamento_dia_semana'),
    sa.ForeignKeyConstraint(['cardapio_item_id'], ['cardapio_itens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planejamento_id'), 'planejamento', ['id'], unique=False)
    op.create_table('receitas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cardapio_item_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('medida_caseira', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cardapio_item_id'], ['cardapio_itens.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['itens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receitas_id'), 'receitas', ['id'], unique=False)
    op.create_table('itens_entrega',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entrega_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('unidade', sa.String(), nullable=True),
    sa.Column('fator_conversao', sa.Float(), nullable=True),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.Column('acao', sa.String(), nullable=False),
    sa.CheckConstraint("acao IN ('recebido', 'alterado', 'excluído')", name='ck_itens_entrega_acao'),
    sa.ForeignKeyConstraint(['entrega_id'], ['entregas.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['itens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_entrega_id'), 'itens_entrega', ['id'], unique=False)
    op.create_table('refeicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('tipo_refeicao', sa.String(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('qtd_alunos', sa.Integer(), nullable=False),
    sa.Column('planejamento_id', sa.Integer(), nullable=True),
    sa.Column('slot', sa.String(), nullable=True),
    sa.Column('nome_extra', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['planejamento_id'], ['planejamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refeicoes_id'), 'refeicoes', ['id'], unique=False)
    op.create_table('refeicao_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refeicao_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_original', sa.Float(), nullable=False),
    sa.Column('quantidade_ajustada', sa.Float(), nullable=False),
    sa.Column('medida_caseira', sa.String(), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['itens.id'], ),
    sa.ForeignKeyConstraint(['refeicao_id'], ['refeicoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refeicao_itens_id'), 'refeicao_itens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refeicao_itens_id'), table_name='refeicao_itens')
    op.drop_table('refeicao_itens')
    op.drop_index(op.f('ix_refeicoes_id'), table_name='refeicoes')
    op.drop_table('refeicoes')
    op.drop_index(op.f('ix_itens_entrega_id'), table_name='itens_entrega')
    op.drop_table('itens_entrega')
    op.drop_index(op.f('ix_receitas_id'), table_name='receitas')
    op.drop_table('receitas')
    op.drop_index(op.f('ix_planejamento_id'), table_name='planejamento')
    op.drop_table('planejamento')
    op.drop_index(op.f('ix_entregas_id'), table_name='entregas')
    op.drop_table('entregas')
    op.drop_index(op.f('ix_conversoes_id'), table_name='conversoes')
    op.drop_table('conversoes')
    op.drop_table('alunos_por_periodo')
    op.drop_index(op.f('ix_usuarios_nome'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_itens_nome'), table_name='itens')
    op.drop_index(op.f('ix_itens_id'), table_name='itens')
    op.drop_table('itens')
    op.drop_index(op.f('ix_fornecedores_nome'), table_name='fornecedores')
    op.drop_index(op.f('ix_fornecedores_id'), table_name='fornecedores')
    op.drop_table('fornecedores')
    op.drop_index(op.f('ix_cardapio_itens_id'), table_name='cardapio_itens')
    op.drop_table('cardapio_itens')
    # ### end Alembic commands ###
